update get sended order

diff --git a/docker/nextjs/Dockerfile b/docker/nextjs/Dockerfile
--- a/docker/nextjs/Dockerfile
+++ b/docker/nextjs/Dockerfile
@@ -1,13 +1,27 @@
-# FROM node:22-alpine AS base
+FROM node:22-alpine AS base
 
-# FROM base AS source
+FROM base AS source
 
-# RUN apk add --no-cache git
+RUN apk add --no-cache git
+RUN apk add --no-cache libc6-compat
+RUN git clone https://github.com/cuongbui1203/lms_fe /app
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+WORKDIR /app
+RUN cp .env.docker .env
+RUN \
+    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    elif [ -f package-lock.json ]; then npm ci; \
+    elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
 
-# RUN git clone https://github.com/cuongbui1203/logistics-management-system-FE /app
-# WORKDIR /app
-# RUN cp .env.docker .env
-# WORKDIR /app
+# USER nextjs
+
+EXPOSE 3000
+RUN mkdir .next/
+ENV PORT 3000
+CMD npm run build;HOSTNAME="0.0.0.0" node ./.next/standalone/server.js
 
 # # Install dependencies only when needed
 # FROM base AS deps
@@ -25,24 +39,6 @@
 #     else echo "Lockfile not found." && exit 1; \
 #     fi
 
-# # Rebuild the source code only when needed
-# FROM base AS builder
-# WORKDIR /app
-# COPY --from=deps /app/node_modules ./node_modules
-# COPY --from=source /app .
-
-# # Next.js collects completely anonymous telemetry data about general usage.
-# # Learn more here: https://nextjs.org/telemetry
-# # Uncomment the following line in case you want to disable telemetry during the build.
-# # ENV NEXT_TELEMETRY_DISABLED 1
-
-# RUN \
-#     if [ -f yarn.lock ]; then yarn run build; \
-#     elif [ -f package-lock.json ]; then npm run build; \
-#     elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
-#     else echo "Lockfile not found." && exit 1; \
-#     fi
-
 # # Production image, copy all the files and run next
 # FROM base AS runner
 # WORKDIR /app
@@ -54,7 +50,8 @@
 # RUN addgroup --system --gid 1001 nodejs
 # RUN adduser --system --uid 1001 nextjs
 
-# COPY --from=builder /app/public ./public
+# COPY --from=source /app/public ./public
+# COPY --from=source /app/src ./src
 
 # # Set the correct permission for prerender cache
 # RUN mkdir .next
@@ -62,8 +59,12 @@
 
 # # Automatically leverage output traces to reduce image size
 # # https://nextjs.org/docs/advanced-features/output-file-tracing
-# COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
-# COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+# # COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+# # COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+# COPY --from=deps /app/node_modules ./node_modules
+# COPY --from=deps /app/package.json /app/yarn.lock* /app/package-lock.json* /app/pnpm-lock.yaml* ./
+# COPY --from=deps /app/.env .env
+
 
 # USER nextjs
 
@@ -73,34 +74,34 @@
 
 # # server.js is created by next build from the standalone output
 # # https://nextjs.org/docs/pages/api-reference/next-config-js/output
-# CMD HOSTNAME="0.0.0.0" node server.js
-FROM node:22-alpine
+# CMD npm run build;HOSTNAME="0.0.0.0" node ./.next/standalone/server.js
+# FROM node:22-alpine
 
-RUN apk add --no-cache git
-RUN apk add --no-cache libc6-compat
-RUN git clone https://github.com/cuongbui1203/logistics-management-system-FE /app
-WORKDIR /app
-RUN cp .env.docker .env
-RUN \
-    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-    elif [ -f package-lock.json ]; then npm ci; \
-    elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
-    else echo "Lockfile not found." && exit 1; \
-    fi
+# RUN apk add --no-cache git
+# RUN apk add --no-cache libc6-compat
+# RUN git clone https://github.com/cuongbui1203/logistics-management-system-FE /app
+# WORKDIR /app
+# RUN cp .env.docker .env
+# RUN \
+#     if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+#     elif [ -f package-lock.json ]; then npm ci; \
+#     elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+#     else echo "Lockfile not found." && exit 1; \
+#     fi
 
-RUN \
-    if [ -f yarn.lock ]; then yarn run build; \
-    elif [ -f package-lock.json ]; then npm run build; \
-    elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
-    else echo "Lockfile not found." && exit 1; \
-    fi
+# RUN \
+#     if [ -f yarn.lock ]; then yarn run build; \
+#     elif [ -f package-lock.json ]; then npm run build; \
+#     elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+#     else echo "Lockfile not found." && exit 1; \
+#     fi
 
-RUN addgroup --system --gid 1001 nodejs
-RUN adduser --system --uid 1001 nextjs
-USER nextjs
+# RUN addgroup --system --gid 1001 nodejs
+# RUN adduser --system --uid 1001 nextjs
+# USER nextjs
 
-ENV PORT 3000
+# ENV PORT 3000
 
-# server.js is created by next build from the standalone output
-# https://nextjs.org/docs/pages/api-reference/next-config-js/output
-CMD HOSTNAME="0.0.0.0" node ./.next/standalone/server.js
+# # server.js is created by next build from the standalone output
+# # https://nextjs.org/docs/pages/api-reference/next-config-js/output
+# CMD HOSTNAME="0.0.0.0" node ./.next/standalone/server.js
